import type { Metadata } from "next"
import { Inter } from "next/font/google"
import './globals.css'

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: 'Portfolio | Diego Chagas - Front-End Developer',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.className} text-gray-900 text-base`}>{children}</body>
    </html>
  );
}
